slam_toolbox:
  ros__parameters:
    # ROS 2 Parametreleri
    use_sim_time: True
    mode: mapping # Haritayı sıfırdan oluştur (Önemli!)

    # Sensör Ayarları
    scan_topic: /scan
    odom_frame: odom
    base_frame: base_footprint
    map_frame: map

    # SLAM Algoritması Ayarları
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0